version: '3'
services:
#  vue-app:
#    build:
#      context: /media/hamor/DOCUMENTS/IdeaProjects/niftylimos-front
#      dockerfile: Dockerfile
#    container_name: vue-app
#    ports:
#      - "8081:80"
#    networks:
#      - mynetwork

  java-app:
    build: .
    container_name: java-app
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=0.0.0.0:5005,server=y,suspend=n
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/niftylimos
    extra_hosts:
      - mysql:192.168.3.4
    depends_on:
      - mysqldb

#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#     - "80:80"
#    volumes:
#      - /media/hamor/DOCUMENTS/IdeaProjects/niftylimos-front/nginx.conf /etc/nginx/nginx.conf
##    entrypoint: [ "/media/hamor/DOCUMENTS/IdeaProjects/niftylimos-front/wait-for-it.sh", "java-app:8080", "command-to-start-nginx" ]
#    depends_on:
#      - java-app
#      - vue-app
#    networks:
#      - mynetwork

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hm21505505
      MYSQL_DATABASE: niftylimos
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: